"""Add active column to products

Revision ID: 888faa415820
Revises: 5735e5a71a12
Create Date: 2026-05-29 13:55:21.274126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '888faa415820'
down_revision = '5735e5a71a12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
